name: Duplicate PR

on:
  issue_comment:
    types: [created, edited]
  
permissions: write-all

jobs:
  duplicate_pr:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '@dimagotchi duplicate this' }}
    runs-on: ubuntu-latest
    steps:
      # - name: Pull Request Comment Branch
      #   uses: xt0rted/pull-request-comment-branch@v2.0.0
      #   id: comment-branch
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dev requirements
        run: pip install sh
        # working-directory: ./commcare-hq
        # run: pip install -r requirements/dev-requirements.txt
      - name: sender
        run: |
          echo sender is ${{ github.event.sender }}
          echo triggering_actor is ${{ github.triggering_actor }}
          echo html_url is ${{github.html_url}}
      - name: Config Git
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
      - name: Run duplicate_pr script
        # run: python scripts/duplicate_pr.py ${{ steps.comment-branch.outputs.head_ref }} ${{ steps.comment-branch.outputs.base_ref }}
        run: python scripts/duplicate_pr.py test2 master
      - name: Create Pull Request Base Master
        if: ${{ steps.comment-branch.outputs.base_ref == "formplayer"}}
        run: gh pr create --title "AUTO PR" --body "AUTO BODY" --base master 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request Base Formplayer
        if: ${{ steps.comment-branch.outputs.base_ref == "master"}}
        run: gh pr create --title "AUTO PR" --body "AUTO BODY" --base formplayer 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # id: cpr
        # uses: peter-evans/create-pull-request@v5
        # with:
        #   title: TITLE
        #   commit-message: Update report
        #   branch: 

  # pr_commented:
  #   # This job only runs for pull request comments
  #   name: PR comment
  #   if: ${{ github.event.issue.pull_request }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo A comment on PR $NUMBER
  #       env:
  #         NUMBER: ${{ github.event.issue.number }}

  # issue_commented:
  #   # This job only runs for issue comments
  #   name: Issue comment
  #   if: ${{ !github.event.issue.pull_request }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo A comment on issue $NUMBER
  #       env:
  #         NUMBER: ${{ github.event.issue.number }}