name: Duplicate PR

on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: created
  

jobs:
  duplicate_pr:
    name: PR comment
    # if: ${{ github.event.issue.pull_request && github.event.comment.body == '@dimagotchi duplicate this' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dev requirements
        run: pip install sh
        # working-directory: ./commcare-hq
        # run: pip install -r requirements/dev-requirements.txt
      - name: Varibles Issue Comment
        run: |
          echo GITHUB_REF_NAME is ${{ github.ref_name }}
          echo GITHUB_BASE_REF is ${{ github.base_ref	}}
          echo event.issue ${{ github.event.issue}}
          echo event.issue.pull_request base.ref ${{ github.event.issue.pull_request.base.ref}}
          echo event.issue.pull_request head.ref ${{ github.event.issue.pull_request.head.ref}}

      - name: Run duplicate_pr script
        # run: python scripts/duplicate_pr.py ${GITHUB_REF_NAME} ${GITHUB_BASE_REF}
        run: python scripts/duplicate_pr.py ${{ github.ref_name }} ${{ github.base_ref }}

  # pr_commented:
  #   # This job only runs for pull request comments
  #   name: PR comment
  #   if: ${{ github.event.issue.pull_request }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo A comment on PR $NUMBER
  #       env:
  #         NUMBER: ${{ github.event.issue.number }}

  # issue_commented:
  #   # This job only runs for issue comments
  #   name: Issue comment
  #   if: ${{ !github.event.issue.pull_request }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo A comment on issue $NUMBER
  #       env:
  #         NUMBER: ${{ github.event.issue.number }}